/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  jloveday
 * Created: 07-Jul-2016
 */
create table IMAGE
(
	ID INTEGER not null primary key generated by default as identity (START WITH 1, INCREMENT BY 1),
	FILE_LOCATION VARCHAR(200),
	FORM VARCHAR(50),
	SECTION_NAME VARCHAR(50),
	TITLE VARCHAR(100)
);
